import './globals.css'
import { Inter } from 'next/font/google'
import Header from "@/components/Header/Header";

import React from "react";
import {useSelector} from "react-redux";
import GlobalLoader from "@/components/Loaders/GlobalLoader";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    const loadingStatus = useSelector(state => state.loading.status)
  return (
    <>
        {loadingStatus && <GlobalLoader />}
        <Header />
        <main>

            {children}
        </main>
    </>



  )
}
